In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

### Q10: Produce a list of facilities with a total revenue less than 1000. The output of facility name and total revenue, sorted by revenue. Remember that there's a different cost for guests and members!

In [3]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT facility, SUM( revenue ) AS total_revenue
FROM (

SELECT f.name AS facility,
CASE WHEN b.memid =0
THEN (
b.slots * guestcost
)
ELSE (
b.slots * membercost
)
END AS revenue
FROM `Bookings` AS b
LEFT JOIN `Members` AS m ON b.memid = m.memid
LEFT JOIN `Facilities` AS f ON b.facid = f.facid
) AS subquery
GROUP BY facility
HAVING total_revenue <1000
ORDER BY total_revenue

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

### Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order

In [9]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT m1.surname, m1.firstname,
    (SELECT m2.firstname 
         WHERE m1.memid = m2.recommendedby 
        AND m2.recommendedby != 0) AS r_fname,
    (SELECT m2.surname
         WHERE m1.memid = m2.recommendedby
        AND m2.recommendedby != 0) AS r_sname
FROM `Members` AS m1
INNER JOIN `Members` AS m2
ON m1.memid = m2.recommendedby
ORDER BY r_sname, r_fname

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Stibbons', 'Ponder', 'Florence', 'Bader')
('Stibbons', 'Ponder', 'Anne', 'Baker')
('Farrell', 'Jemima', 'Timothy', 'Baker')
('Rownam', 'Tim', 'Tim', 'Boothe')
('Smith', 'Darren', 'Gerald', 'Butters')
('Baker', 'Timothy', 'Joan', 'Coplin')
('Smith', 'Tracy', 'Erica', 'Crumpet')
('Joplette', 'Janice', 'Nancy', 'Dare')
('Butters', 'Gerald', 'Matthew', 'Genting')
('Purview', 'Millicent', 'John', 'Hunt')
('Joplette', 'Janice', 'David', 'Jones')
('Jones', 'David', 'Douglas', 'Jones')
('Smith', 'Darren', 'Janice', 'Joplette')
('Smith', 'Darren', 'Anna', 'Mackenzie')
('Smith', 'Darren', 'Charles', 'Owen')
('Farrell', 'Jemima', 'David', 'Pinker')
('Smith', 'Tracy', 'Millicent', 'Purview')
('Genting', 'Matthew', 'Henrietta', 'Rumney')
('Bader', 'Florence', 'Ramnaresh', 'Sarwin')
('Smith', 'Darren', 'Jack', 'Smith')
('Tracy', 'Burton', 'Ponder', 'Stibbons')
('Smith', 'Tracy', 'Henry', 'Worthington-Smyth')

### Q12: Find the facilities with their usage by member, but not guests

In [7]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT 
    f.name AS facility,
    SUM(slots)
FROM `Bookings` AS b
LEFT JOIN `Facilities` AS f
ON b.facid = f.facid
LEFT JOIN `Members` AS m
ON b.memid = m.memid
WHERE b.memid !=0
GROUP BY facility
ORDER BY SUM(slots)DESC

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1086)
('Tennis Court 1', 957)
('Massage Room 1', 884)
('Tennis Court 2', 882)
('Snooker Table', 860)
('Pool Table', 856)
('Table Tennis', 794)
('Squash Court', 418)
('Massage Room 2', 54)

### Q13: Find the facilities usage by month, but not guests

In [ ]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT 
    MONTH(b.starttime) AS month,
    f.name AS facility,
    SUM(slots)
FROM `Bookings` AS b
LEFT JOIN `Facilities` AS f
ON b.facid = f.facid
LEFT JOIN `Members` AS m
ON b.memid = m.memid
WHERE b.memid !=0
GROUP BY month, facility
ORDER BY facility
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()